"""Review node for generating the structured peer review."""

from __future__ import annotations

import json
import logging

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from agent.errors import format_model_error, is_expected_model_auth_error
from agent.prompts import REVIEW_NODE_SYSTEM_PROMPT
from agent.state import AgentState
from core.config import settings

logger = logging.getLogger(__name__)

VALID_RECOMMENDATIONS = {"Accept", "Minor revision", "Major revision", "Reject"}


JSON_REPAIR_SYSTEM_PROMPT = """You repair malformed JSON generated by a peer-review model.
Return ONLY one valid JSON object. Do not add markdown, commentary, or extra keys.
If the input is truncated, preserve all complete information and close incomplete
strings, arrays, and objects with concise professional text."""


def _strip_json_fences(raw_text: str) -> str:
    """Remove markdown fences from model output when present."""
    text = raw_text.strip()
    if text.startswith("```"):
        parts = text.split("```")
        if len(parts) > 1:
            text = parts[1]
        if text.startswith("json"):
            text = text[4:]
    return text.strip()


def _load_json_output(raw_text: str) -> dict:
    """Parse a model response that should contain a single JSON object."""
    parsed = json.loads(_strip_json_fences(raw_text))
    if not isinstance(parsed, dict):
        raise json.JSONDecodeError("Expected top-level JSON object", raw_text, 0)
    return parsed


def _as_list(value: object) -> list:
    """Normalize model values that should be JSON arrays."""
    return value if isinstance(value, list) else []


def _as_text(value: object, default: str = "") -> str:
    """Normalize nullable model text fields."""
    return value if isinstance(value, str) else default


def _as_optional_score(value: object) -> float | None:
    """Convert nullable model scores into a float or None."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _normalize_dimension_scores(value: object) -> list[dict]:
    """Normalize dimension scores so downstream persistence never crashes."""
    normalized = []
    for item in _as_list(value):
        if not isinstance(item, dict):
            continue
        normalized.append(
            {
                "dimension": _as_text(item.get("dimension"), "Unspecified"),
                "score": _as_optional_score(item.get("score")) or 0.0,
                "strengths": [str(v) for v in _as_list(item.get("strengths"))],
                "weaknesses": [str(v) for v in _as_list(item.get("weaknesses"))],
                "critical_issues": [str(v) for v in _as_list(item.get("critical_issues"))],
                "suggestions": [str(v) for v in _as_list(item.get("suggestions"))],
            }
        )
    return normalized


def _normalize_recommendation(value: object) -> str | None:
    """Keep only recommendations supported by the database enum."""
    return value if isinstance(value, str) and value in VALID_RECOMMENDATIONS else None


def _desk_rejection_from_research_analysis(state: AgentState) -> dict:
    """Build a completed result for documents that are not research manuscripts."""
    analysis = state.get("research_analysis", {})
    detected_type = _as_text(analysis.get("document_type_detected"), "non-research document")
    reason = _as_text(
        analysis.get("desk_rejection_reason"),
        f"The uploaded document appears to be a {detected_type}, not a research manuscript.",
    )
    summary = (
        f"The uploaded document appears to be a {detected_type}. "
        "It cannot be assessed with the research manuscript peer-review workflow."
    )
    comments = (
        f"{reason} A reviewable research manuscript should include a clear research question, "
        "methods or study design, results or findings, discussion or conclusions, and a reference list. "
        "Please upload a complete research manuscript if you want a full peer-review report."
    )
    return {
        "dimension_scores": [],
        "overall_score": None,
        "recommendation": None,
        "summary": summary,
        "general_comments": comments,
        "major_flaws": [],
        "minor_points": [],
        "related_papers": [],
        "status": "complete",
    }


def _normalize_review_data(review_data: dict) -> dict:
    """Normalize model JSON to the shape expected by persistence and UI."""
    desk_rejected = bool(review_data.get("desk_rejected"))
    overall_score = _as_optional_score(review_data.get("overall_score"))
    recommendation = _normalize_recommendation(review_data.get("recommendation"))

    if not desk_rejected and overall_score is None:
        overall_score = 5.0
    if desk_rejected:
        recommendation = None

    return {
        "dimension_scores": _normalize_dimension_scores(review_data.get("dimension_scores")),
        "overall_score": overall_score,
        "recommendation": recommendation,
        "summary": _as_text(review_data.get("summary")),
        "general_comments": _as_text(review_data.get("general_comments")),
        "major_flaws": _as_list(review_data.get("major_flaws")),
        "minor_points": [str(v) for v in _as_list(review_data.get("minor_points"))],
        "status": "complete",
    }


def _build_review_prompt(state: AgentState) -> str:
    """Build the user prompt from extracted paper and literature data."""
    sections_text = "\n\n".join(
        f"=== {name.upper()} ===\n{content[:3000]}"
        for name, content in state.get("sections", {}).items()
    )
    related_papers_text = "\n".join(
        f"- {paper.get('title', 'Unknown')} ({paper.get('year', 'N/A')}) — {paper.get('citation_count', 0)} citations"
        for paper in state.get("related_papers", [])[:10]
    )
    references_text = "\n".join(
        f"- {reference.get('title', 'Unknown')} ({reference.get('year', 'N/A')})"
        for reference in state.get("references", [])[:20]
    )
    research_analysis_text = json.dumps(state.get("research_analysis", {}), indent=2)

    return f"""PAPER TO REVIEW
===============
Title: {state.get('title', 'Unknown')}
Authors: {', '.join(state.get('authors', []))}
Field: {state.get('field', 'Unknown')}
Word count: {state.get('word_count', 0)} | Pages: {state.get('page_count', 0)}

ABSTRACT:
{state.get('abstract', 'Not available')}

PAPER SECTIONS:
{sections_text}

FIGURES ({len(state.get('figures', []))} total):
{chr(10).join(state.get('figures', [])[:10])}

TABLES ({len(state.get('tables', []))} total):
{chr(10).join(state.get('tables', [])[:10])}

REFERENCES:
{references_text if references_text else 'No references extracted'}

RELATED PAPERS FROM SEMANTIC SCHOLAR:
{related_papers_text if related_papers_text else 'No related papers found'}

RESEARCH ANALYSIS:
{research_analysis_text}

INSTRUCTIONS:
Produce a complete, rigorous peer review of this paper following your system prompt.
Every critical issue must cite a specific section, table, or figure.
Return ONLY valid JSON."""


async def review_node(state: AgentState) -> dict:
    """Generate the final structured review with Gemini Pro."""
    updates: dict = {"progress_messages": [*state.get("progress_messages", [])]}
    if state.get("status") == "failed":
        return updates
    if state.get("research_analysis", {}).get("document_type_valid") is False:
        updates["progress_messages"].append("Skipping full peer review for non-research document.")
        updates.update(_desk_rejection_from_research_analysis(state))
        return updates

    try:
        updates["progress_messages"].append(
            "Running peer review analysis with Gemini Pro (this takes 30-60 seconds)..."
        )
        llm = ChatGoogleGenerativeAI(
            model=settings.GEMINI_PRO_MODEL,
            temperature=0.2,
            google_api_key=settings.GEMINI_API_KEY,
            max_output_tokens=16000,
            response_mime_type="application/json",
        )
        response = await llm.ainvoke(
            [
                SystemMessage(content=REVIEW_NODE_SYSTEM_PROMPT),
                HumanMessage(content=_build_review_prompt(state)),
            ]
        )
        raw_output = str(response.content).strip()
        updates["review_llm_raw_output"] = raw_output
        try:
            review_data = _load_json_output(raw_output)
        except json.JSONDecodeError as exc:
            logger.warning("Initial review JSON parse failed, attempting repair: %s", exc)
            updates["progress_messages"].append("Repairing malformed review JSON...")
            repair_response = await llm.ainvoke(
                [
                    SystemMessage(content=JSON_REPAIR_SYSTEM_PROMPT),
                    HumanMessage(content=f"Malformed JSON to repair:\n{raw_output}"),
                ]
            )
            repaired_output = str(repair_response.content).strip()
            updates["review_llm_raw_output"] = repaired_output
            review_data = _load_json_output(repaired_output)
        normalized_review_data = _normalize_review_data(review_data)

        validated_flaws = []
        for flaw in normalized_review_data.get("major_flaws", []):
            if not isinstance(flaw, dict):
                continue
            evidence = flaw.get("evidence", "")
            if evidence and any(
                keyword in evidence.lower()
                for keyword in ["section", "table", "figure", "abstract", "line", "page", "eq"]
            ):
                validated_flaws.append(flaw)
        normalized_review_data["major_flaws"] = validated_flaws

        updates.update(normalized_review_data)
        score_text = f"{updates['overall_score']:.1f}/10" if updates["overall_score"] is not None else "N/A"
        recommendation_text = updates["recommendation"] or "Not applicable"
        updates["progress_messages"].append(
            f"Review complete. Score: {score_text} — {recommendation_text}"
        )
    except json.JSONDecodeError as exc:
        logger.error("Failed to parse review JSON: %s", exc, exc_info=True)
        updates.setdefault("review_llm_raw_output", raw_output if "raw_output" in locals() else "")
        updates["error"] = (
            "Review JSON parse error after repair attempt. "
            "The model returned malformed or truncated JSON. Please retry this review."
        )
        updates["status"] = "failed"
    except Exception as exc:
        user_message = format_model_error(exc)
        logger.error(
            "review_node error: %s",
            user_message,
            exc_info=not is_expected_model_auth_error(exc),
        )
        updates.setdefault("review_llm_raw_output", raw_output if "raw_output" in locals() else "")
        updates["error"] = f"Review node failed: {user_message}"
        updates["status"] = "failed"

    return updates
