"""Review node for generating the structured peer review."""

from __future__ import annotations

import json
import logging

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from agent.errors import format_model_error, is_expected_model_auth_error
from agent.progress import emit_progress
from agent.prompts import REVIEW_NODE_SYSTEM_PROMPT
from agent.state import AgentState
from core.config import settings

logger = logging.getLogger(__name__)

VALID_RECOMMENDATIONS = {"Accept", "Minor revision", "Major revision", "Reject"}
ORIGINALITY_DIMENSION_KEYWORDS = ("originality", "significance", "novelty")
ETHICS_DIMENSION_KEYWORDS = ("ethics", "reproducibility", "open science")


JSON_REPAIR_SYSTEM_PROMPT = """You repair malformed JSON generated by a peer-review model.
Return ONLY one valid JSON object. Do not add markdown, commentary, or extra keys.
If the input is truncated, preserve all complete information and close incomplete
strings, arrays, and objects with concise professional text."""

REVIEW_VALIDATION_SYSTEM_PROMPT = """You are a senior meta-reviewer and quality-control editor.
Audit an AI-generated peer review before it is shown to authors.

Return ONLY valid JSON with this exact schema:
{
  "passes_validation": true,
  "validation_findings": ["string"],
  "corrected_review": null
}

Set passes_validation=false and provide corrected_review when you find any of:
- recommendation inconsistent with the score thresholds
- overall_score not equal to the weighted dimension formula
- major flaw without specific manuscript evidence
- claims not supported by the provided manuscript excerpts or research analysis
- generic feedback that should be made more specific
- missing acknowledgement that no major flaws were identified

The corrected_review must preserve the original review schema and should edit
only what is necessary. Do not invent citations, tables, figures, or section
numbers that are not present in the manuscript excerpts."""


def _strip_json_fences(raw_text: str) -> str:
    """Remove markdown fences from model output when present."""
    text = raw_text.strip()
    if text.startswith("```"):
        parts = text.split("```")
        if len(parts) > 1:
            text = parts[1]
        if text.startswith("json"):
            text = text[4:]
    return text.strip()


def _load_json_output(raw_text: str) -> dict:
    """Parse a model response that should contain a single JSON object."""
    parsed = json.loads(_strip_json_fences(raw_text))
    if not isinstance(parsed, dict):
        raise json.JSONDecodeError("Expected top-level JSON object", raw_text, 0)
    return parsed


def _as_list(value: object) -> list:
    """Normalize model values that should be JSON arrays."""
    return value if isinstance(value, list) else []


def _as_text(value: object, default: str = "") -> str:
    """Normalize nullable model text fields."""
    return value if isinstance(value, str) else default


def _as_optional_score(value: object) -> float | None:
    """Convert nullable model scores into a float or None."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _normalize_dimension_scores(value: object) -> list[dict]:
    """Normalize dimension scores so downstream persistence never crashes."""
    normalized = []
    for item in _as_list(value):
        if not isinstance(item, dict):
            continue
        normalized.append(
            {
                "dimension": _as_text(item.get("dimension"), "Unspecified"),
                "score": _as_optional_score(item.get("score")) or 0.0,
                "strengths": [str(v) for v in _as_list(item.get("strengths"))],
                "weaknesses": [str(v) for v in _as_list(item.get("weaknesses"))],
                "critical_issues": [str(v) for v in _as_list(item.get("critical_issues"))],
                "suggestions": [str(v) for v in _as_list(item.get("suggestions"))],
            }
        )
    return normalized


def _normalize_recommendation(value: object) -> str | None:
    """Keep only recommendations supported by the database enum."""
    return value if isinstance(value, str) and value in VALID_RECOMMENDATIONS else None


def _calculate_weighted_score(dimension_scores: list[dict]) -> float | None:
    """Calculate the rubric-weighted score when all six dimensions are present."""
    weights = {
        "originality": 0.20,
        "methodology": 0.25,
        "data": 0.20,
        "figures": 0.10,
        "presentation": 0.10,
        "ethics": 0.15,
    }
    found: dict[str, float] = {}
    for item in dimension_scores:
        dimension = _as_text(item.get("dimension")).lower()
        score = _as_optional_score(item.get("score"))
        if score is None:
            continue
        for key in weights:
            if key in dimension and key not in found:
                found[key] = max(0.0, min(10.0, score))
                break
    if len(found) != len(weights):
        return None
    return round(sum(found[key] * weight for key, weight in weights.items()), 1)


def _recommendation_for_score(score: float | None, major_flaws: list) -> str | None:
    """Return a conservative recommendation suggested by score and major flaws."""
    if score is None:
        return None
    has_critical = any(
        isinstance(item, dict) and _as_text(item.get("severity")).lower().startswith("critical")
        for item in major_flaws
    )
    if has_critical or score < 4.0:
        return "Reject"
    if score < 6.0 or len(major_flaws) >= 3:
        return "Major revision"
    if score < 7.5 or major_flaws:
        return "Minor revision"
    return "Accept"


def _is_already_published(state: AgentState) -> bool:
    """Return True when the literature search found the submitted paper itself."""
    publication_check = state.get("publication_check") or state.get("research_analysis", {}).get("publication_check") or {}
    return publication_check.get("status") == "already_published"


def _cap_dimension_scores_for_duplicate(dimension_scores: list[dict]) -> list[dict]:
    """Cap originality and ethics dimensions when the manuscript is already published."""
    for item in dimension_scores:
        dimension = _as_text(item.get("dimension")).lower()
        if any(keyword in dimension for keyword in ORIGINALITY_DIMENSION_KEYWORDS):
            item["score"] = min(float(item.get("score", 0.0)), 1.0)
            weaknesses = item.setdefault("weaknesses", [])
            if isinstance(weaknesses, list):
                weaknesses.append("Semantic Scholar returned the manuscript itself as an already published work.")
            critical_issues = item.setdefault("critical_issues", [])
            if isinstance(critical_issues, list):
                critical_issues.append("Originality cannot be credited for a manuscript that appears already published.")
        if any(keyword in dimension for keyword in ETHICS_DIMENSION_KEYWORDS):
            item["score"] = min(float(item.get("score", 0.0)), 2.0)
            critical_issues = item.setdefault("critical_issues", [])
            if isinstance(critical_issues, list):
                critical_issues.append("Possible duplicate-publication/submission risk detected from literature search.")
    return dimension_scores


def _apply_publication_duplicate_guardrail(review_data: dict, state: AgentState) -> dict:
    """Force review consistency when the uploaded manuscript appears already published."""
    already_published = _is_already_published(state)
    if not already_published:
        return review_data

    publication_check = state.get("publication_check") or state.get("research_analysis", {}).get("publication_check") or {}
    matched_title = _as_text(publication_check.get("matched_title"), "the submitted manuscript")
    matched_year = publication_check.get("matched_year") or "N/A"
    matched_venue = publication_check.get("matched_venue") or "Semantic Scholar"
    evidence = (
        "Related Literature / Semantic Scholar: exact or near-exact title match "
        f"'{matched_title}' ({matched_year}, {matched_venue})."
    )

    review_data["recommendation"] = "Reject"
    review_data["overall_score"] = None
    review_data["dimension_scores"] = []
    review_data["already_published"] = True

    duplicate_flaw = {
        "issue": "Already-published manuscript detected",
        "evidence": evidence,
        "remedy": (
            "Do not submit an already published paper as a new manuscript. If this is intended as a "
            "post-publication assessment, label it explicitly and remove publication-decision scoring."
        ),
        "severity": "critical",
    }
    flaws = [item for item in _as_list(review_data.get("major_flaws")) if isinstance(item, dict)]
    if not any("published" in _as_text(item.get("issue")).lower() or "duplicate" in _as_text(item.get("issue")).lower() for item in flaws):
        flaws.insert(0, duplicate_flaw)
    review_data["major_flaws"] = flaws

    warning = (
        "This paper appears to be already published. The review process has been stopped and no originality "
        "or overall score is assigned."
    )
    existing_summary = _as_text(review_data.get("summary"))
    review_data["summary"] = f"{warning} {existing_summary}".strip()
    existing_comments = _as_text(review_data.get("general_comments"))
    review_data["general_comments"] = f"{warning}\n\n{existing_comments}".strip()
    return review_data


def _desk_rejection_from_research_analysis(state: AgentState) -> dict:
    """Build a completed result for documents that are not research manuscripts."""
    analysis = state.get("research_analysis", {})
    detected_type = _as_text(analysis.get("document_type_detected"), "non-research document")
    reason = _as_text(
        analysis.get("desk_rejection_reason"),
        f"The uploaded document appears to be a {detected_type}, not a research manuscript.",
    )
    summary = (
        f"The uploaded document appears to be a {detected_type}. "
        "It cannot be assessed with the research manuscript peer-review workflow."
    )
    comments = (
        f"{reason} A reviewable research manuscript should include a clear research question, "
        "methods or study design, results or findings, discussion or conclusions, and a reference list. "
        "Please upload a complete research manuscript if you want a full peer-review report."
    )
    return {
        "dimension_scores": [],
        "overall_score": None,
        "recommendation": None,
        "summary": summary,
        "general_comments": comments,
        "major_flaws": [],
        "minor_points": [],
        "related_papers": [],
        "status": "complete",
    }


def _normalize_review_data(review_data: dict) -> dict:
    """Normalize model JSON to the shape expected by persistence and UI."""
    desk_rejected = bool(review_data.get("desk_rejected"))
    already_published = bool(review_data.get("already_published"))
    overall_score = _as_optional_score(review_data.get("overall_score"))
    recommendation = _normalize_recommendation(review_data.get("recommendation"))

    if already_published:
        overall_score = None
        recommendation = "Reject"
    elif not desk_rejected and overall_score is None:
        overall_score = 5.0
    if desk_rejected:
        recommendation = None

    normalized_dimensions = [] if already_published else _normalize_dimension_scores(review_data.get("dimension_scores"))
    weighted_score = _calculate_weighted_score(normalized_dimensions)
    if not already_published and not desk_rejected and weighted_score is not None:
        overall_score = weighted_score

    major_flaws = _as_list(review_data.get("major_flaws"))
    suggested_recommendation = _recommendation_for_score(overall_score, major_flaws)
    if not already_published and not desk_rejected and suggested_recommendation:
        if recommendation is None:
            recommendation = suggested_recommendation
        elif recommendation == "Accept" and suggested_recommendation != "Accept":
            recommendation = suggested_recommendation

    return {
        "dimension_scores": normalized_dimensions,
        "overall_score": overall_score,
        "recommendation": recommendation,
        "summary": _as_text(review_data.get("summary")),
        "general_comments": _as_text(review_data.get("general_comments")),
        "major_flaws": major_flaws,
        "minor_points": [str(v) for v in _as_list(review_data.get("minor_points"))],
        "status": "complete",
    }


def _build_review_prompt(state: AgentState) -> str:
    """Build the user prompt from extracted paper and literature data."""
    sections_text = "\n\n".join(
        f"=== {name.upper()} ===\n{content[:3000]}"
        for name, content in state.get("sections", {}).items()
    )
    related_papers_text = "\n".join(
        f"- {paper.get('title', 'Unknown')} ({paper.get('year', 'N/A')}) — {paper.get('citation_count', 0)} citations"
        for paper in state.get("related_papers", [])[:10]
    )
    references_text = "\n".join(
        f"- {reference.get('title', 'Unknown')} ({reference.get('year', 'N/A')})"
        for reference in state.get("references", [])[:20]
    )
    research_analysis_text = json.dumps(state.get("research_analysis", {}), indent=2)
    publication_check_text = json.dumps(state.get("publication_check", {}), indent=2)

    prompt = f"""PAPER TO REVIEW
===============
Title: {state.get('title', 'Unknown')}
Authors: {', '.join(state.get('authors', []))}
Field: {state.get('field', 'Unknown')}
Word count: {state.get('word_count', 0)} | Pages: {state.get('page_count', 0)}

ABSTRACT:
{state.get('abstract', 'Not available')}

PAPER SECTIONS:
{sections_text}

FIGURES ({len(state.get('figures', []))} total):
{chr(10).join(state.get('figures', [])[:10])}

TABLES ({len(state.get('tables', []))} total):
{chr(10).join(state.get('tables', [])[:10])}

REFERENCES:
{references_text if references_text else 'No references extracted'}

RELATED PAPERS FROM SEMANTIC SCHOLAR:
{related_papers_text if related_papers_text else 'No related papers found'}

RESEARCH ANALYSIS:
{research_analysis_text}

PUBLICATION DUPLICATE CHECK:
{publication_check_text}

INSTRUCTIONS:
Produce a complete, rigorous peer review of this paper following your system prompt.
If publication_check.status is already_published, treat it as a fatal originality/publication-ethics issue:
recommend Reject, set originality/novelty score no higher than 1/10, and explain the matched publication.
Every critical issue must cite a specific section, table, or figure.
Return ONLY valid JSON."""

    openreview_block = state.get("openreview_examples_prompt", "")
    if openreview_block and openreview_block.strip():
        prompt += f"\n\n{openreview_block}"

    return prompt


def _build_validation_prompt(state: AgentState, review_data: dict) -> str:
    """Build a compact validation prompt for second-pass review quality control."""
    section_excerpts = "\n\n".join(
        f"=== {name.upper()} ===\n{content[:1200]}"
        for name, content in state.get("sections", {}).items()
    )
    related_papers = [
        {
            "title": paper.get("title"),
            "year": paper.get("year"),
            "relevance_note": paper.get("relevance_note"),
        }
        for paper in state.get("related_papers", [])[:8]
    ]
    return f"""SUBMITTED MANUSCRIPT CONTEXT
Title: {state.get('title', 'Unknown')}
Authors: {', '.join(state.get('authors', []))}
Field: {state.get('field', 'Unknown')}
Abstract:
{state.get('abstract', 'Not available')[:3000]}

Research analysis:
{json.dumps(state.get('research_analysis', {}), ensure_ascii=False, indent=2)}

Related papers:
{json.dumps(related_papers, ensure_ascii=False, indent=2)}

Manuscript section excerpts:
{section_excerpts[:9000]}

AI-generated review to validate:
{json.dumps(review_data, ensure_ascii=False, indent=2)}

Audit the review against the manuscript context and the scoring rubric.
If it is acceptable, return passes_validation=true and corrected_review=null.
If not, return passes_validation=false and corrected_review with the full corrected review JSON."""


async def _run_second_pass_validation(llm: ChatGoogleGenerativeAI, state: AgentState, review_data: dict) -> tuple[dict, dict]:
    """Run a non-fatal meta-review validation pass and return possibly corrected data."""
    response = await llm.ainvoke(
        [
            SystemMessage(content=REVIEW_VALIDATION_SYSTEM_PROMPT),
            HumanMessage(content=_build_validation_prompt(state, review_data)),
        ]
    )
    validation_raw = str(response.content).strip()
    validation_data = _load_json_output(validation_raw)
    corrected = validation_data.get("corrected_review")
    if isinstance(corrected, dict):
        return corrected, validation_data
    return review_data, validation_data


async def review_node(state: AgentState) -> dict:
    """Generate the final structured review with Gemini Pro."""
    updates: dict = {"progress_messages": [*state.get("progress_messages", [])]}
    if state.get("status") == "failed":
        return updates
    if state.get("research_analysis", {}).get("document_type_valid") is False:
        updates["progress_messages"].append("Skipping full peer review for non-research document.")
        updates.update(_desk_rejection_from_research_analysis(state))
        return updates

    try:
        updates["progress_messages"].append(
            "Running peer review analysis with Gemini Pro (this takes 30-60 seconds)..."
        )
        await emit_progress(state["review_id"], "reviewing", "Running peer review analysis")
        llm = ChatGoogleGenerativeAI(
            model=settings.GEMINI_PRO_MODEL,
            temperature=0.2,
            google_api_key=settings.GEMINI_API_KEY,
            max_output_tokens=16000,
            response_mime_type="application/json",
        )
        response = await llm.ainvoke(
            [
                SystemMessage(content=REVIEW_NODE_SYSTEM_PROMPT),
                HumanMessage(content=_build_review_prompt(state)),
            ]
        )
        raw_output = str(response.content).strip()
        updates["review_llm_raw_output"] = raw_output
        try:
            review_data = _load_json_output(raw_output)
        except json.JSONDecodeError as exc:
            logger.warning("Initial review JSON parse failed, attempting repair: %s", exc)
            updates["progress_messages"].append("Repairing malformed review JSON...")
            repair_response = await llm.ainvoke(
                [
                    SystemMessage(content=JSON_REPAIR_SYSTEM_PROMPT),
                    HumanMessage(content=f"Malformed JSON to repair:\n{raw_output}"),
                ]
            )
            repaired_output = str(repair_response.content).strip()
            updates["review_llm_raw_output"] = repaired_output
            review_data = _load_json_output(repaired_output)
        review_data = _apply_publication_duplicate_guardrail(review_data, state)
        validation_data: dict = {
            "passes_validation": None,
            "validation_findings": ["Second-pass validation was not run."],
            "corrected_review": None,
        }
        if not review_data.get("already_published") and not review_data.get("desk_rejected"):
            try:
                updates["progress_messages"].append("Running second-pass review validation...")
                validation_llm = ChatGoogleGenerativeAI(
                    model=settings.GEMINI_FLASH_MODEL,
                    temperature=0,
                    google_api_key=settings.GEMINI_API_KEY,
                    max_output_tokens=12000,
                    response_mime_type="application/json",
                )
                review_data, validation_data = await _run_second_pass_validation(validation_llm, state, review_data)
            except Exception as exc:
                logger.warning("Second-pass review validation failed; using initial review: %s", exc)
                validation_data = {
                    "passes_validation": False,
                    "validation_findings": [f"Validation pass failed non-fatally: {format_model_error(exc)}"],
                    "corrected_review": None,
                }
        updates["review_llm_raw_output"] = json.dumps(
            {
                "initial_review": raw_output,
                "validation": {
                    "passes_validation": validation_data.get("passes_validation"),
                    "validation_findings": validation_data.get("validation_findings", []),
                    "corrected_review_applied": isinstance(validation_data.get("corrected_review"), dict),
                },
                "final_review": review_data,
            },
            ensure_ascii=False,
        )
        normalized_review_data = _normalize_review_data(review_data)

        validated_flaws = []
        for flaw in normalized_review_data.get("major_flaws", []):
            if not isinstance(flaw, dict):
                continue
            evidence = flaw.get("evidence", "")
            if evidence and any(
                keyword in evidence.lower()
                for keyword in ["section", "table", "figure", "abstract", "line", "page", "eq", "semantic scholar", "related literature"]
            ):
                validated_flaws.append(flaw)
        if _is_already_published(state) and not any(
            "published" in _as_text(item.get("issue")).lower()
            for item in validated_flaws
            if isinstance(item, dict)
        ):
            publication_check = state.get("publication_check") or {}
            validated_flaws.insert(
                0,
                {
                    "issue": "Already-published manuscript detected",
                    "evidence": (
                        "Related Literature / Semantic Scholar: exact or near-exact title match "
                        f"'{publication_check.get('matched_title', state.get('title', 'submitted manuscript'))}'."
                    ),
                    "remedy": "Do not submit an already published paper as a new manuscript.",
                    "severity": "critical",
                },
            )
        normalized_review_data["major_flaws"] = validated_flaws

        updates.update(normalized_review_data)
        score_text = f"{updates['overall_score']:.1f}/10" if updates["overall_score"] is not None else "N/A"
        recommendation_text = updates["recommendation"] or "Not applicable"
        updates["progress_messages"].append(
            f"Review complete. Score: {score_text} — {recommendation_text}"
        )
    except json.JSONDecodeError as exc:
        logger.error("Failed to parse review JSON: %s", exc, exc_info=True)
        updates.setdefault("review_llm_raw_output", raw_output if "raw_output" in locals() else "")
        updates["error"] = (
            "Review JSON parse error after repair attempt. "
            "The model returned malformed or truncated JSON. Please retry this review."
        )
        updates["status"] = "failed"
    except Exception as exc:
        user_message = format_model_error(exc)
        logger.error(
            "review_node error: %s",
            user_message,
            exc_info=not is_expected_model_auth_error(exc),
        )
        updates.setdefault("review_llm_raw_output", raw_output if "raw_output" in locals() else "")
        updates["error"] = f"Review node failed: {user_message}"
        updates["status"] = "failed"

    return updates
