import { ArrowLeft, BookOpenCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const sections = [
  {
    title: '1. Acceptance of these terms',
    body: [
      'By creating an account, uploading a manuscript, or using AI Research Reviewer, you agree to these Terms of Service. If you do not agree, do not use the service.',
      'These terms apply to the public AI Research Reviewer web application and any review reports generated through it.',
    ],
  },
  {
    title: '2. Purpose of the service',
    body: [
      'AI Research Reviewer is a pre-submission manuscript review assistant. It helps authors identify potential reviewer concerns, quality signals, improvement areas, and presentation issues before formal journal, conference, supervisor, or internal review.',
      'The service provides decision-support feedback only. It is not a publisher, journal, peer-review board, ethics committee, legal advisor, plagiarism authority, or substitute for qualified human judgment.',
    ],
  },
  {
    title: '3. Your responsibilities',
    body: [
      'You may only upload manuscripts, PDFs, abstracts, metadata, or other research materials that you have the right and authority to process through the service.',
      'You are responsible for complying with your institution, funder, journal, conference, employer, collaborator, and confidentiality obligations before submitting any unpublished or sensitive work.',
      'You must not upload unlawful content, content that violates another person\'s rights, malicious files, or material that you are prohibited from sharing with external processing tools.',
    ],
  },
  {
    title: '4. AI-generated review output',
    body: [
      'Review scores, recommendations, comments, summaries, related-literature notes, and suggested revisions are generated by automated systems and may be incomplete, inaccurate, outdated, or inappropriate for a specific venue.',
      'You should independently verify important claims, citations, research-integrity issues, methodology concerns, publication strategy, and ethical conclusions before relying on the output.',
      'The service does not guarantee acceptance, publication, peer-review success, citation impact, originality, novelty, or compliance with any journal or conference policy.',
    ],
  },
  {
    title: '5. Manuscript handling',
    body: [
      'Submitted manuscripts are processed to generate a review report and show the result to the submitting user. We do not sell submitted manuscripts, publish them, or use them to create public datasets.',
      'The application may retain account records, review metadata, generated feedback, downloadable reports, and operational records as needed to provide review history, account access, troubleshooting, abuse prevention, and service maintenance.',
      'You can request deletion of your account or review records by contacting the service operator through the support channel provided for this deployment.',
    ],
  },
  {
    title: '6. Accounts and security',
    body: [
      'You are responsible for keeping your login credentials secure and for activity that occurs under your account.',
      'Notify the service operator promptly if you believe your account has been accessed without permission.',
    ],
  },
  {
    title: '7. Acceptable use',
    body: [
      'You must not attempt to disrupt the service, bypass security controls, scrape protected areas, reverse engineer private systems, overload the application, or use the service to process content for which you lack permission.',
      'We may restrict, suspend, or terminate access if we reasonably believe an account is being misused, creates security risk, violates these terms, or may harm other users or the service.',
    ],
  },
  {
    title: '8. Intellectual property',
    body: [
      'You retain ownership of manuscripts and materials you submit. Subject to the Privacy Policy, you grant the service the limited permission needed to process those materials and generate your review report.',
      'The application interface, software, design, documentation, and service name remain the property of their respective owners. You may not copy or redistribute the service as your own product without permission.',
    ],
  },
  {
    title: '9. Disclaimers and limitation of liability',
    body: [
      'The service is provided on an as-is and as-available basis. We do not warrant that it will be uninterrupted, error-free, secure, or suitable for every manuscript, venue, or research discipline.',
      'To the fullest extent permitted by law, the service operator is not liable for publication decisions, missed issues, inaccurate feedback, loss of data, confidentiality decisions made by users, or indirect, incidental, consequential, or special damages arising from use of the service.',
    ],
  },
  {
    title: '10. Changes',
    body: [
      'We may update these terms as the service evolves. The updated version will be posted on this page with a new effective date when material changes are made.',
    ],
  },
];

export function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5">
          <Link to="/" className="flex items-center gap-3 font-bold text-slate-950">
            <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-700 text-white">
              <BookOpenCheck className="h-5 w-5" />
            </span>
            AI Research Reviewer
          </Link>
          <Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700 hover:text-blue-900">
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
        </div>
      </header>

      <div className="mx-auto max-w-5xl px-5 py-10">
        <article className="bg-white px-8 py-9 shadow-sm ring-1 ring-slate-200 sm:px-10">
          <p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-700">Effective date: May 10, 2026</p>
          <h1 className="mt-3 text-4xl font-bold tracking-normal text-slate-950">Terms of Service</h1>
          <p className="mt-4 max-w-3xl text-base font-medium leading-7 text-slate-500">
            These terms explain how AI Research Reviewer may be used and what users should understand before submitting manuscripts for automated review.
          </p>

          <div className="mt-10 space-y-8">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-xl font-bold tracking-normal text-slate-950">{section.title}</h2>
              <div className="mt-4 space-y-3">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="text-sm font-medium leading-7 text-slate-600">{paragraph}</p>
                ))}
              </div>
            </section>
          ))}
          </div>
        </article>
      </div>
    </main>
  );
}
